platform :ios, '8.0'

target 'BasicExample' do
  # Only Core to use location services and analytics tracking
  pod 'InsiteoSDKCore', :podspec => 'https://raw.github.com/Insiteo/ios-v4/master/InsiteoSDKCore.podspec'
end
